apiVersion: v1
kind: ServiceAccount
metadata:
  name: openemr-sa
  namespace: openemr
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: openemr
  name: openemr-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openemr-rolebinding
  namespace: openemr
subjects:
- kind: ServiceAccount
  name: openemr-sa
  namespace: openemr
roleRef:
  kind: Role
  name: openemr-role
  apiGroup: rbac.authorization.k8s.io
